modLoader="javafml" #mandatory
loaderVersion="[37,)"
issueTrackerURL="https://github.com/TeamTwilight/crossdimcommands/issues"
license="LGPL 2.1"

[[mods]]
modId="crossdimcommands"
version="1.0"
displayName="Cross-DimCommands"
authors="jodlodi"
credits="Thanks to the rest of TeamTwilight for being so awesome :)"
description='''
Small mod that allows "weather" commands to be used from any dimension and properly translates coordinates inputted into the "worldborder center" command.
'''

[[dependencies.crossdimcommands]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.0,)"
    ordering="NONE"
    side="BOTH"